### ISSUE TITLE
Variable nodes like Unreal Engine

### ISSUE THREAD

**Issue by bhouston** [bhouston/behave-graph#120]
In Unreal Engine things are a little tricky with variable nodes:

1) "get variable" nodes have no title, just a single output socket named after the variable name.
2) "Set variable" nodes have the name "Set" and a single input socket named after the variable name.

![HT45](https://user-images.githubusercontent.com/588541/196066570-7efd1548-7788-4cef-aa31-32db77faeb17.jpeg)

This should be replicated in this tool.

**Comment by beeglebug** [comment]
Am I right in thinking that the second one in the image (a "get" node)
isn't really a node in the graph, it's just a visual representation of a
variable (from the variables part of the JSON) which looks similar to a
node in the UI?
