### ISSUE TITLE
feature request: glb/gltf extension for behavior graphs

### ISSUE THREAD

**Issue by oveddan** [bhouston/behave-graph#125]
I'm a huge fan of what this lib offers, thanks for getting this together.  Have you thought of making a spec of a gltf extension for these behavior graphs and then allowing the graphs to be loaded with the gltf in a single json, and having it run by loading that extension?

**Comment by bhouston** [comment]
Ask and you shall receive: https://github.com/KhronosGroup/glTF/pull/2191. Please note that this extension is influx and is highly influenced by this open source project and vice versa.  It is an official initiative from the glTF standards committee to push this extension forward and this open source repository is intended to be an implementation of a behavior graph that is conferment to the specification.

**Comment by oveddan** [comment]
wow awesome, glad to see this repo will align with that spec! thanks for sharing
