### ISSUE TITLE
Dev issue: running yarn prettier:fix results in many outstanding changes.

### ISSUE THREAD

**Issue by oveddan** [bhouston/behave-graph#130]
I would like to be able to consistently run `yarn prettier:fix` as part of my dev workflow (to keep the code nicely formatted) but when I do there become many outstanding changes:

<img width="479" alt="Screenshot 2022-10-31 at 1 58 35 PM" src="https://user-images.githubusercontent.com/891755/199076969-0f657001-e0a4-4207-9fd2-25fd060d8ae7.png">

<img width="455" alt="Screenshot 2022-10-31 at 1 58 40 PM" src="https://user-images.githubusercontent.com/891755/199076989-3a7ba692-0088-4e34-8892-9a009a365cc5.png">

It would be nice if these were all fixed so that as developers we can run that command regularly and only affect the code we are working on.

**Comment by bhouston** [comment]
fixed in this PR: https://github.com/bhouston/behave-graph/pull/139
