### ISSUE TITLE
Bug: three.js demo doesn't run anymore

### ISSUE THREAD

**Issue by oveddan** [bhouston/behave-graph#140]
Since the recent changes, running the three.js demo is broken:

First it gives you the error: 
```
index.ts:171 Uncaught (in promise) Error: no registered abstraction with name ILifecycleEventEmitter
    at AbstractionsRegistry.get (AbstractionsRegistry.ts:14:13)
    at LifecycleOnTick.init (LifecycleOnTick.ts:46:42)
    at Engine.ts:28:54
    at Array.forEach (<anonymous>)
    at new Engine (Engine.ts:28:21)
    at main (index.ts:130:18)`
```

Then if you move the abstraction registries higher, you get:

`TypeError: node must be an instance of ImmediateNod`

**Comment by bhouston** [comment]
I'll have a look know.

**Comment by bhouston** [comment]
fixed here: https://github.com/bhouston/behave-graph/commit/7364d7cd984c9878869204844720341bf09697d4
