### ISSUE TITLE
Feature request:  node type of Step/Counter

### ISSUE THREAD

**Issue by oveddan** [bhouston/behave-graph#148]
Would be nice to have a Step/Counter node type, that every time it receives a flow, an output value is incremented.

Suggested params:
* start value
* increment (how much to increment by every time a signal is received)

**Comment by bhouston** [comment]
I will implement this!

**Comment by bhouston** [comment]
Implemented here: https://github.com/bhouston/behave-graph/commit/b32cad1e66d25cb2893ef4a6d28d5a166dd2822a
