### ISSUE TITLE
How to handle nodes with varying numbers of sockets?  Sequence and Multi-gate?

### ISSUE THREAD

**Issue by bhouston** [bhouston/behave-graph#150]
In unreal engine and Unity, sequence and multi-gate nodes are allowed to have an unlimited number of output sockets.  In the UI it is possible to add and remove output sockets which form a numbered sequence.

https://docs.unrealengine.com/4.26/en-US/ProgrammingAndScripting/Blueprints/UserGuide/FlowControl/

![Sequence_Example](https://user-images.githubusercontent.com/588541/201370586-9ed04930-e8dd-4e2b-9ecb-a13281c7509e.png)

Basically they have an "add pin" button on the UX which adds a new pin.  

"Though not really an output pin, this button allows you to add as many outputs as you like. Outputs can be removed by right-clicking and choosing Remove Output Pin."

Behave-graph supports this behavior now because I just look through all output sockets.  So if you manually create additional output sockets it will trigger them.  IS this sufficient for the core library?  We leave the adding/removing output sockets to the UX libraries or other users of behave-graph?

Alternatively, I could add a "add socket", "remove socket" functionality on certain nodes.  Then this could be interpreted by the UX library to add these menu options?

**Comment by oveddan** [comment]
What if you had an input parameter "sequenceSteps" that auto-generats the corresponding # of output sockets?

**Comment by bhouston** [comment]
I have added a number to the name of these nodes.  So the nodes themselves are not dynamic.  Rather instead there is a sequence/1 sequence/2 sequence/3, etc nodes.  Each with a different number of output nodes.  This was implemented in this PR: https://github.com/bhouston/behave-graph/pull/163
