### ISSUE TITLE
Fix css in graph-editor

### ISSUE THREAD

**Issue by bhouston** [bhouston/behave-graph#169]
This is for either @oveddan or @beeglebug, who ever can fix it.  The graph editor currently looks like this:

<img width="1792" alt="Screenshot 2022-11-29 at 8 01 54 PM" src="https://user-images.githubusercontent.com/588541/204682390-d33b9c60-5a68-48d1-ba24-bd7f87a03056.png">

**Comment by oveddan** [comment]
I'll take a look at this!
