### ISSUE TITLE
Move Scene Profile outside the core package

### ISSUE THREAD

**Issue by aitorllj93** [bhouston/behave-graph#197]
I think the Scene Profile doesn't make sense to be in the **@behave-graph/core** package, I would move it to an external package like **@behave-graph/scene**. This would also make easier to notice about which code should be publicly available from the core module to be able to create custom profiles.

**Comment by bhouston** [comment]
I can do that. :). Or if you wanted to give it a try?

**Comment by bhouston** [comment]
Done!
