### ISSUE TITLE
Spelling mistake: Uniary -> Unary

### ISSUE THREAD

**Issue by bhouston** [bhouston/behave-graph#33]
@javagl pointed out this spelling mistake.

**Comment by javagl** [comment]
That was only one that jumped out for me. I didn't make a real "review" (and if I did, I'd either point our or simply create a PR for things like the missing `n` in [`numberLessThaOrEqual`](https://github.com/bhouston/behave-graph/blob/598f87a927dafb01985753a6718bf76ac73d3060/src/lib/Nodes/Generic/GenericNodes.ts#L102)). Depending on how buried I'm with other tasks, I might actually have a closer look at this repo at some point, but right now, there still are some higher-level discussion points that are more important than nitpicking about typos...
