### ISSUE TITLE
Setup package alias so one can import in examples easily.

### ISSUE THREAD

**Issue by bhouston** [bhouston/behave-graph#42]
it would be nice to see in the examples this:
```
import { Node } from 'behaviour-graph';
```
Rather than:
```
import { Node } from '../../../dist/lib/index';
```

I think this can be done with some config variables in the tsconfig.json file...

**Comment by beeglebug** [comment]
now that the examples are being bundled, they don't need to be importing from the `dist` version, they can go straight to src. they will still be relative links though, but this is only the same as in any other file in the src directory

**Comment by bhouston** [comment]
okay.  Did you want to have a go at this?

**Comment by bhouston** [comment]
I did what @beeglebug recommended.  It works great!
