### ISSUE TITLE
dist has two copies of the library and type definitions

### ISSUE THREAD

**Issue by beeglebug** [bhouston/behave-graph#48]
this is causing vscode to show everything twice in autocomplete, possibly no other side effects, but should tidy up anyway

i think this was introduced when the examples got bundled, the `del` commands probably need double checking

<img width="685" alt="image" src="https://user-images.githubusercontent.com/954416/182949589-b11ae796-b0e8-4749-9d2e-ea1097b5e3bd.png">

**Comment by bhouston** [comment]
I don't see this in the /dist folder.  But I may need to setup a separate project that references this package in order to test this out.  I will do this soon.  Sorry about that @beeglebug

**Comment by beeglebug** [comment]
seems to have stopped as of 0.0.5
