### ISSUE TITLE
Bug: triggerEvents with outputs doesn't apply provided value

### ISSUE THREAD

**Issue by evilfant** [bhouston/behave-graph#62]
[Codesandbox  with reproduction](https://codesandbox.io/s/cool-euclid-rk6h5q?file=/src/main.js:1341-1355)

I added custom event node (`StartWithOutputNode`) with output socket
I want to trigger this node with value
```js
graphEvaluator.triggerEvents(
    "event/startWithOutput",
    new Map([["str", "provided string"]])
);
```

Expected: "provided string" in log
Actual: empty message in log

**Comment by bhouston** [comment]
fixed by above PR.

**Comment by bhouston** [comment]
thank you!
