### ISSUE TITLE
nodes attempting to set output values on flow sockets

### ISSUE THREAD

**Issue by beeglebug** [bhouston/behave-graph#69]
Several flow nodes are throwing errors when you attempt to run a graph, complaining about attempting to set output values on flow sockets.

I think i've fixed flipflop, as that was the one I was attempting to use when I saw the issue, but I suspect some of the others are still doing it (I was hesitant to touch things like "flow/sequence" which seem incomplete anyway)

**Comment by bhouston** [comment]
I will create an example with FlipFlop.  I had only prototyped it and never tested it.  Probably is using an older design.

**Comment by bhouston** [comment]
I think I fixed Sequence and ForLoop.

**Comment by bhouston** [comment]
FlipFlop example added, incorporated into the tests as well.
