### ISSUE TITLE
how does a graph connect to an external environment?

### ISSUE THREAD

**Issue by beeglebug** [bhouston/behave-graph#70]
This is a larger question about how a behave-graph graph interacts/binds itself to some external environment, be it a threejs scene or something else.

This codesandbox is me experimenting with a simple connection between a graph and a threejs scene, but at the moment the connection is very manual.

https://codesandbox.io/s/behave-graph-three-test-ijdzj6

What i'm wondering, is what do we think that connection will eventually look like?  I imagine a node such as my test "input/mouseClick" would also have an input of some sort to select a mesh in the scene (in this case the cube), and then would only be triggered by clicks on that cube.

We would then also want a way to transmit effects back into the scene, for example I might want a graph which looks like the following:

```
const graphDef: GraphJSON = {
  nodes: [
    {
      id: "1",
      type: "input/mouseClick",
    },
    {
      id: "2",
      type: "material/setColor",
      inputs: {
        text: {
          value: "#0000FF",
        },
        flow: {
          links: [
            {
              nodeId: "1",
              socket: "flow",
            },
          ],
        },
      },
    },
  ],
};
```

ie, when the user clicks on the cube, the material changes colour to blue.

I think it would be really useful to sketch out some more "real world" examples of graphs which actually do something in a less abstract environment to get an idea of what changes might be required in the core library to support the required nodes.

**Comment by bhouston** [comment]
To be clear, I've added the ability to register "implementations" of "abstractions".  The abstractions are what nodes use.  But you can register an implementation of them with the graph registry.  This allows you to map the abstractions that nodes use onto real-world aspects of your system.

Here is an example in our default console graph evaluator:

https://github.com/bhouston/behave-graph/blob/main/src/examples/exec-graph/index.ts#L15

```
registry.implementations.register('ILogger', new DefaultLogger());
const manualLifecycleEventEmitter = new ManualLifecycleEventEmitter();
registry.implementations.register('ILifecycleEventEmitter', manualLifecycleEventEmitter);
```

Here I register a simple logger that just outputs to the console.  And I register a manual lifecycle event emitter that I can just simple control.
