### ISSUE TITLE
add prettier config

### ISSUE THREAD

**Issue by beeglebug** [bhouston/behave-graph#71]
From experience, prettier is the nicest solution to keeping a clean, consistently formatted codebase while removing any possible arguments about the details. It's used by thousands of other open source JS projects, so contributors will be familiar with it.

We could auto format everything once in a single cleanup commit and be done with it, most modern IDE's will handle prettier automatically and format on save.

We can then strip out most of the eslint config (certainly any bits pertaining to code formatting).

**Comment by bhouston** [comment]
I had eslint doing cleanup on save in VSCode with all of the auto-formatting.  I think you removed this file that enabled that:

https://github.com/bhouston/behave-graph/blob/e596cf818bf034a66b66e9b87c3ca0f46c23eb1f/.vscode/settings.json

Could we just re-enable that?  Then this task is done and we do not need prettier.

**Comment by bhouston** [comment]
Here is your commit where you removed this: https://github.com/bhouston/behave-graph/commit/684df3d76f5c651d8a767bec093fe1bea42270a1

**Comment by bhouston** [comment]
I've added back auto-formatting via es-lint on save here: https://github.com/bhouston/behave-graph/blob/main/.vscode/settings.json

**Comment by beeglebug** [comment]
The problem with this approach is firstly that vscode settings file is a userland file and not really intended for sharing between developers (and obviously only works for people with vscode).

Secondly eslint is not really a code formatter, it can highlight code issues, but it's slightly out of scope to handle spacing, braces etc. That's where prettier comes in. Ideally we would use both, and let them do their own things.
